### ISSUE TITLE
ID is not always surrounded with brackets

### ISSUE THREAD

**Issue by akkie** [liamwh/surreal-id#25]
The actual implementation always checks if the ID part is surrounded with brackets. But only an ID with complex characters like a UUID needs to be surrounded with either \` or `⟨ ⟩` characters.

An ULID or custom string ID's do not need to be surrounded.

https://docs.surrealdb.com/docs/surrealql/datamodel/ids/

**Comment by liamwh** [comment]
Hi @akkie , thanks for pointing this out. You are correct that those types do not need to be surrounded with the special characters. However, the point of this library is to be generic in ensuring that regardless of the type you use as an ID, it will always be able to be successfully serialized and deserialised from SurrealDB. As far as I am aware, standardising that all IDs are wrapped in the special characters is the only way to do this, so I don't currently plan on addressing your point. Note that you can use the [id_without_brackets](https://docs.rs/surreal-id/0.2.1/surreal_id/trait.NewId.html#method.id_without_brackets) method to get the id without the brackets in your Rust code. And feel free to open a PR if you have a means to make the API more flexible whilst ensuring all ID types are consistently successfully serialised and deserialised!

Thanks, Liam
